import '@bryntum/calendar/calendar.stockholm.css';
import type { Metadata } from 'next';
import { Poppins } from 'next/font/google';
import StoryblokProvider from './components/StoryblokProvider';
import StoryDataProvider from './contexts/StoryData.context';
import './globals.css';

const poppins = Poppins({
    weight   : ['400', '500', '600', '700'],
    subsets  : ['latin'],
    variable : '--font-poppins'
});

export const metadata: Metadata = {
    title       : 'Create Next App',
    description : 'Generated by create next app'
};

export default function RootLayout({
    children
}: Readonly<{
  children: React.ReactNode;
}>) {
    return (
        <StoryblokProvider>
            <StoryDataProvider>
                <html lang="en" className={poppins.className}>
                    <body>
                        {children}
                    </body>
                </html>
            </StoryDataProvider>
        </StoryblokProvider>
    );
}
